'use client';

// Patient-facing Terms of Service for the Cardioplace v2 pilot.
//
// Counsel-applied content (v2026-05-20). Previous counsel-reviewed
// version was v2026-05-08; this revision adds: algorithmic-alert
// disclosure (§2), emergency-contact recommendation (§3), Google
// Gemini voice-BAA disclosure (§6), Privacy Policy + NPP cross-
// reference (§8), no-charge-during-pilot statement (§9), Terms-
// change notification process (§11), data retention + deletion
// rights (§12). Do not edit wording without legal/compliance sign-off.

import {
  PolicyContact,
  PolicySection,
  PolicyShell,
} from '@/components/cardio/policy/PolicyShell';

export default function TermsPage() {
  return (
    <PolicyShell
      kind="terms"
      title="Terms of Service"
      intro="Cardioplace is a remote monitoring and communication platform operated by Healplace.com, Inc. in partnership with participating healthcare organizations."
      lastUpdated="May 20, 2026"
    >
      <PolicySection number="1" title="Introduction">
        <p>
          Cardioplace is a remote monitoring and communication platform
          operated by Healplace.com, Inc. in partnership with participating
          healthcare organizations.
        </p>
        <p>
          By creating an account and acknowledging these Terms during
          onboarding, you agree to these Terms.
        </p>
      </PolicySection>

      <PolicySection number="2" title="What Cardioplace does">
        <p>Cardioplace helps patients:</p>
        <ul className="list-disc pl-6 space-y-1.5">
          <li>Track blood pressure and symptoms.</li>
          <li>Share information with care teams.</li>
          <li>Receive alerts and follow-up communication.</li>
          <li>Support longitudinal monitoring between visits.</li>
        </ul>
        <p>
          Cardioplace uses physician-authored rules and automated workflows
          to identify readings or symptoms that may require review.
        </p>
        <p>
          Alerts are generated by automated rules signed off by a licensed
          physician. They are not a substitute for clinical judgment by your
          care team.
        </p>
      </PolicySection>

      <PolicySection number="3" title="Important medical disclaimer">
        <div
          className="rounded-r-lg px-5 py-4 space-y-3"
          style={{
            backgroundColor: '#FEF2F2',
            borderLeft: '4px solid #DC2626',
          }}
        >
          <p>
            Cardioplace is not an emergency service and is not continuously
            monitored in real time.
          </p>
          <p>
            Cardioplace does not diagnose, treat, or cure medical conditions.
            The platform supports monitoring and communication only.
          </p>
          <p className="font-semibold" style={{ color: '#170c1d' }}>
            If you experience chest pain, difficulty breathing, severe
            headache, stroke symptoms, suicidal thoughts, or any medical
            emergency, call 911 or seek emergency medical care immediately.
            Do not wait for a message from Cardioplace.
          </p>
        </div>
        <p>
          We recommend you designate an emergency contact (a family member,
          neighbor, or trusted person) who knows you use Cardioplace and can
          respond if needed. You can share this information with your care
          team during onboarding.
        </p>
      </PolicySection>

      <PolicySection number="4" title="Eligibility">
        <p>You must:</p>
        <ul className="list-disc pl-6 space-y-1.5">
          <li>Be at least 18 years old.</li>
          <li>Reside in the United States.</li>
          <li>Be associated with a participating clinic or care organization.</li>
          <li>
            Be capable of providing informed consent or have a legally
            authorized representative.
          </li>
        </ul>
      </PolicySection>

      <PolicySection number="5" title="Account access">
        <p>
          You access Cardioplace using secure email-based authentication.
        </p>
        <p>You are responsible for:</p>
        <ul className="list-disc pl-6 space-y-1.5">
          <li>Maintaining access to your email account.</li>
          <li>Protecting your sign-in credentials.</li>
          <li>Informing us if unauthorized access occurs.</li>
        </ul>
      </PolicySection>

      <PolicySection number="6" title="Information you provide">
        <p>You may provide:</p>
        <ul className="list-disc pl-6 space-y-1.5">
          <li>Health conditions.</li>
          <li>Medications.</li>
          <li>Symptoms.</li>
          <li>Blood pressure readings.</li>
          <li>Pregnancy status.</li>
          <li>Messages and voice interactions.</li>
        </ul>
        <p>
          Voice interactions may be transcribed and stored as part of your
          clinical communication record for patient-safety review and care
          coordination.
        </p>
        <p>
          Voice transcription is performed by Google&apos;s Gemini AI
          service under a Business Associate Agreement. Your voice data is
          not used to train commercial AI models.
        </p>
      </PolicySection>

      <PolicySection number="7" title="Care team review">
        <p>
          Your care team may review and verify information you provide.
          Until verification occurs, the platform may apply conservative
          default safety rules.
        </p>
      </PolicySection>

      <PolicySection number="8" title="Privacy of your information">
        <p>
          Your protected health information (PHI) is handled in accordance
          with our{' '}
          <a
            href="/privacy"
            className="font-semibold underline underline-offset-2"
            style={{ color: 'var(--brand-primary-purple, #7B00E0)' }}
          >
            Privacy Policy
          </a>{' '}
          and the federal Health Insurance Portability and Accountability
          Act (HIPAA).
        </p>
        <p>
          You will also receive a separate Notice of Privacy Practices
          describing how your health information is used, shared, and
          protected. By using Cardioplace, you acknowledge you have received
          or have access to this Notice.
        </p>
      </PolicySection>

      <PolicySection number="9" title="Pilot status">
        <p>
          Some deployments of Cardioplace operate as pilot-stage services
          undergoing active clinical evaluation. Features may change over
          time.
        </p>
        <p>
          During the pilot, use of Cardioplace is provided at no charge to
          participating patients.
        </p>
        <p>
          While we work to maintain reliability, delays or interruptions may
          occur.
        </p>
      </PolicySection>

      <PolicySection number="10" title="Acceptable use">
        <p>You agree:</p>
        <ul className="list-disc pl-6 space-y-1.5">
          <li>To provide accurate information.</li>
          <li>Not to enter another person&apos;s readings under your account.</li>
          <li>Not to interfere with or misuse the platform.</li>
          <li>To follow measurement instructions where applicable.</li>
        </ul>
      </PolicySection>

      <PolicySection number="11" title="Termination">
        <p>
          You may stop using Cardioplace at any time by contacting your care
          team or{' '}
          <a
            href="mailto:support@healplace.com"
            className="font-semibold underline underline-offset-2"
            style={{ color: 'var(--brand-primary-purple, #7B00E0)' }}
          >
            support@healplace.com
          </a>
          .
        </p>
        <p>
          We may suspend access where necessary for safety, compliance, or
          operational reasons.
        </p>
      </PolicySection>

      <PolicySection number="12" title="How long we keep your information">
        <p>
          Your account information and health data are retained for as long
          as your account is active and for an additional period required by
          law or applicable medical-records retention policies (typically
          seven years for adult medical records in the District of Columbia).
        </p>
        <p>
          You may request deletion of your account by contacting{' '}
          <a
            href="mailto:support@healplace.com"
            className="font-semibold underline underline-offset-2"
            style={{ color: 'var(--brand-primary-purple, #7B00E0)' }}
          >
            support@healplace.com
          </a>
          . Deletion is subject to applicable medical-records retention
          requirements.
        </p>
      </PolicySection>

      <PolicySection number="13" title="Changes to these Terms">
        <p>
          We may update these Terms from time to time. If we make material
          changes, we will notify you by email or through the platform
          before the changes take effect. Continued use of Cardioplace after
          the effective date constitutes acceptance of the updated Terms.
        </p>
      </PolicySection>

      <PolicySection number="14" title="Limitation of liability">
        <p>
          To the maximum extent permitted by law, Healplace.com, Inc. is not
          liable for indirect or consequential damages arising from use of
          the platform, except where prohibited by law.
        </p>
      </PolicySection>

      <PolicySection number="15" title="Governing law">
        <p>These Terms are governed by the laws of the District of Columbia.</p>
      </PolicySection>

      <PolicyContact
        heading="Contact"
        emails={['support@healplace.com', 'privacy@healplace.com']}
      />
    </PolicyShell>
  );
}
